import { Geist, Geist_Mono } from "next/font/google";
import { Quicksand } from "next/font/google";
import "./globals.css";

const quicksand_init = Quicksand({
  subsets: ['latin'],
  weight: ['500'],
  variable: '--font-quicksand',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="quicksand">
      <body
        className={quicksand_init.variable}
      >
        {children}
      </body>
    </html>
  );
}
